name: Lastest Hashnode Blog Post
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
    # Run cron every 12 hours
    # - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Hashnode blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "HASHNODE"
          commit_message: "Updated readme with the latest Hashnode Blog data"
          feed_list: "https://blog.dhairyapatel.in/rss.xml"
